name: dyce_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  go_router: ^9.0.3

  #FIREBASE
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.0
  firebase_storage: ^11.2.5

  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  dartz: ^0.10.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  riverpod_lint: ^2.0.1
  animated_native_splash: ^1.3.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    -  assets/
    -  assets/images/
    -  assets/icons/
    -  assets/projects_images/farmguard/
    -  assets/projects_images/edutive/
    -  assets/projects_images/decorride/
    -  assets/projects_images/ecocaasitech_agent/
    -  assets/projects_images/ecocaasitech_owner/
    -  assets/projects_images/mbelemama/
    -  assets/projects_images/kropco/
    -  assets/projects_images/one_market_vendor/
    -  assets/projects_images/portfolio_app/
    -  assets/projects_images/scriptlens/
    -  assets/projects_images/one_market_customer/

animated_native_splash:
  # jsonFile is the only required parameter.This the file use to setup the animation object.
  # jsonFile: assets/bouncing_loading.json
  jsonFile: assets/Loading_1.json
